### ISSUE TITLE
Documentation for static export

### ISSUE THREAD

**Issue by benoitchantre** [capsule-corp-ternoa/nft-marketplace#271]
Hello,

I'm not sure this is the right place for documentation related issues.

I was trying to build a static version of the app using `npm run export` and faced some errors because of a missing `exportPathMap` in `next.config.js`.

Would it be possible to cover static export configuration in the documentation?

Thanks

**Comment by Leouarz** [comment]
Hello, 

In the current state, this app has an extensive use of "getServerSideProps" which is not compatible with static export.
Actually running an npm run export (after installing and building) gets me to the same conclusion : 
```
Error: Export encountered errors on following paths:
        /
        /[name]
        /create
        /explore
        /faq
        /nft/[name]
        /profile
        /success
        /wallet
```
And for each you also have : 
```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Error for page /: pages with `getServerSideProps` can not be exported. See more info here: https://nextjs.org/docs/messages/gssp-export
```

The solution if you want to deploy your own version would be to pass those "getServerSideProps" in client side of next app then try exporting again.

Don't hesitate if you have any questions.

Closing this issue for now.

**Comment by benoitchantre** [comment]
Thank you for the detailed answer
