### ISSUE TITLE
Package upgrade

### ISSUE THREAD

**Issue by soufiane-bouchaara** [capsule-corp-ternoa/nft-marketplace#377]
<img width="558" alt="image" src="https://user-images.githubusercontent.com/2540416/185332324-35ea5b51-b329-44db-89a8-01d2936f7dc9.png">

**Comment by ipapandinas** [comment]
Hi
Thank you for this package review, however the code for this Marketplace is not currently supported, I leave this issue pending.

**Comment by ipapandinas** [comment]
This project is no longer maintained, the repository is archived.
